apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  volumeName: mysql-pv #el mismo nombre del archivo pv
  accessModes:
    #- ReadWriteOnce
    - ReadWriteMany
  storageClassName: ""
  #storageClassName: standard
  resources:
    requests:
      storage: 2Gi