apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  volumeName: postgres-pv #el mismo nombre del archivo pv
  accessModes:
    - ReadWriteMany
    #- ReadWriteOnce
  storageClassName: ""
  #storageClassName: standard
  resources:
    requests:
      storage: 2Gi