apiVersion: v1
kind: Secret
metadata:
  name: msvc-usuarios
type: Opaque
data:
  #decodificado en base 64
  username: cm9vdA==
  password: c2FzYQ==

---
apiVersion: v1
kind: Secret
metadata:
  name: msvc-cursos
type: Opaque
data:
  #decodificado en base 64
  username: cG9zdGdyZXM=
  password: c2FzYQ==
